module.exports = [
    "Western Africa",
    "Western Asia",
    "Western Europe",
    "Western Sahara",
    "World",
    "AFRICA", 
    "ASIA",
    "Central America",
    "Central Asia",
    "Eastern Africa",
    "Eastern Asia",
    "Eastern Europe",
    "EUROPE",
    "LATIN AMERICA AND THE CARIBBEAN",
    "Least developed countries",
    "Less developed regions",
    "Less developed regions, excluding China",
    "Less developed regions, excluding least developed countries",
    "Middle Africa",
    "More developed regions",
    "Northern Africa",
    "NORTHERN AMERICA",
    "Northern Europe",
    "Other non-specified areas",
    "Sub-Saharan Africa",
    "Australia/New Zealand",
    "South America",
    "South-Central Asia",
    "South-Eastern Asia",
    "Southern Africa",
    "Southern Asia",
    "Southern Europe",
    "Sub-Saharan Africa",
]